name: Test Coveralls

on: ['push', 'pull_request']

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
