name: Pre-Release
'on':
  push:
    branches:
      - next

env:
  # Disable husky
  HUSKY: 0

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Bump version

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v3
        with:
          # this seems to be needed by lerna to work as expected
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup git
        run: |
          git config --global user.name "Bump version - ${{ github.repository }} (by ${{ github.actor }})"
          git config --global user.email "${{ github.repository }}-version-bump@users.noreply.github.com"

      - run: yarn install
      - run: yarn build
      - run: yarn ci:release:pre
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
